name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install depenciencies
      run: |
        sudo apt-get update
        sudo apt-get install python3
        sudo apt-get install make
    - name: Setup Virtual Environment and Install Python Dependencies
      run: |
        sudo make env
        
    - name: Clean Environment
      run: |
        make clean
